global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['host.docker.internal:8001'] # Adjust port if needed

  - job_name: 'postgres'
    static_configs:
      - targets: ['host.docker.internal:9187']